<?php

declare(strict_types=1);

/**
 * SPDX-FileCopyrightText: 2026 cpcMomentum
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

namespace OCA\Rechnungswerk\Service;

/**
 * Laendernamen zu ISO-3166-1-alpha-2-Codes, deutsch und englisch.
 *
 * GENERIERT - nicht von Hand bearbeiten. Quelle sind die 250 Codes aus
 * horstoeko/zugferd (ZugferdCountryCodes, die fuer EN16931 zulaessige Liste),
 * die Namen stammen aus den CLDR-Daten der PHP-Extension intl.
 *
 * Neu erzeugen mit dem Generator aus PR #171 (siehe Issue #167):
 * die Tabelle wird bewusst committet, damit zur Laufzeit keine
 * intl-Extension noetig ist - Nextcloud selbst behandelt intl als optional.
 *
 * @psalm-type CountryNames = array{0: string, 1: string}
 */
final class CountryData {

	/**
	 * Code => [deutscher Name, englischer Name]
	 *
	 * @var array<string, array{0: string, 1: string}>
	 */
	public const NAMES = [
		'1A' => ['Kosovo', 'Kosovo'],
		'AD' => ['Andorra', 'Andorra'],
		'AE' => ['Vereinigte Arabische Emirate', 'United Arab Emirates'],
		'AF' => ['Afghanistan', 'Afghanistan'],
		'AG' => ['Antigua und Barbuda', 'Antigua & Barbuda'],
		'AI' => ['Anguilla', 'Anguilla'],
		'AL' => ['Albanien', 'Albania'],
		'AM' => ['Armenien', 'Armenia'],
		'AO' => ['Angola', 'Angola'],
		'AQ' => ['Antarktis', 'Antarctica'],
		'AR' => ['Argentinien', 'Argentina'],
		'AS' => ['Amerikanisch-Samoa', 'American Samoa'],
		'AT' => ['Österreich', 'Austria'],
		'AU' => ['Australien', 'Australia'],
		'AW' => ['Aruba', 'Aruba'],
		'AX' => ['Ålandinseln', 'Åland Islands'],
		'AZ' => ['Aserbaidschan', 'Azerbaijan'],
		'BA' => ['Bosnien und Herzegowina', 'Bosnia & Herzegovina'],
		'BB' => ['Barbados', 'Barbados'],
		'BD' => ['Bangladesch', 'Bangladesh'],
		'BE' => ['Belgien', 'Belgium'],
		'BF' => ['Burkina Faso', 'Burkina Faso'],
		'BG' => ['Bulgarien', 'Bulgaria'],
		'BH' => ['Bahrain', 'Bahrain'],
		'BI' => ['Burundi', 'Burundi'],
		'BJ' => ['Benin', 'Benin'],
		'BL' => ['St. Barthélemy', 'St. Barthélemy'],
		'BM' => ['Bermuda', 'Bermuda'],
		'BN' => ['Brunei Darussalam', 'Brunei'],
		'BO' => ['Bolivien', 'Bolivia'],
		'BQ' => ['Karibische Niederlande', 'Caribbean Netherlands'],
		'BR' => ['Brasilien', 'Brazil'],
		'BS' => ['Bahamas', 'Bahamas'],
		'BT' => ['Bhutan', 'Bhutan'],
		'BV' => ['Bouvetinsel', 'Bouvet Island'],
		'BW' => ['Botsuana', 'Botswana'],
		'BY' => ['Belarus', 'Belarus'],
		'BZ' => ['Belize', 'Belize'],
		'CA' => ['Kanada', 'Canada'],
		'CC' => ['Kokosinseln', 'Cocos (Keeling) Islands'],
		'CD' => ['Kongo-Kinshasa', 'Congo - Kinshasa'],
		'CF' => ['Zentralafrikanische Republik', 'Central African Republic'],
		'CG' => ['Kongo-Brazzaville', 'Congo - Brazzaville'],
		'CH' => ['Schweiz', 'Switzerland'],
		'CI' => ['Côte d’Ivoire', 'Côte d’Ivoire'],
		'CK' => ['Cookinseln', 'Cook Islands'],
		'CL' => ['Chile', 'Chile'],
		'CM' => ['Kamerun', 'Cameroon'],
		'CN' => ['China', 'China'],
		'CO' => ['Kolumbien', 'Colombia'],
		'CR' => ['Costa Rica', 'Costa Rica'],
		'CU' => ['Kuba', 'Cuba'],
		'CV' => ['Cabo Verde', 'Cape Verde'],
		'CW' => ['Curaçao', 'Curaçao'],
		'CX' => ['Weihnachtsinsel', 'Christmas Island'],
		'CY' => ['Zypern', 'Cyprus'],
		'CZ' => ['Tschechien', 'Czechia'],
		'DE' => ['Deutschland', 'Germany'],
		'DJ' => ['Dschibuti', 'Djibouti'],
		'DK' => ['Dänemark', 'Denmark'],
		'DM' => ['Dominica', 'Dominica'],
		'DO' => ['Dominikanische Republik', 'Dominican Republic'],
		'DZ' => ['Algerien', 'Algeria'],
		'EC' => ['Ecuador', 'Ecuador'],
		'EE' => ['Estland', 'Estonia'],
		'EG' => ['Ägypten', 'Egypt'],
		'EH' => ['Westsahara', 'Western Sahara'],
		'ER' => ['Eritrea', 'Eritrea'],
		'ES' => ['Spanien', 'Spain'],
		'ET' => ['Äthiopien', 'Ethiopia'],
		'FI' => ['Finnland', 'Finland'],
		'FJ' => ['Fidschi', 'Fiji'],
		'FK' => ['Falklandinseln', 'Falkland Islands'],
		'FM' => ['Mikronesien', 'Micronesia'],
		'FO' => ['Färöer', 'Faroe Islands'],
		'FR' => ['Frankreich', 'France'],
		'GA' => ['Gabun', 'Gabon'],
		'GB' => ['Vereinigtes Königreich', 'United Kingdom'],
		'GD' => ['Grenada', 'Grenada'],
		'GE' => ['Georgien', 'Georgia'],
		'GF' => ['Französisch-Guayana', 'French Guiana'],
		'GG' => ['Guernsey', 'Guernsey'],
		'GH' => ['Ghana', 'Ghana'],
		'GI' => ['Gibraltar', 'Gibraltar'],
		'GL' => ['Grönland', 'Greenland'],
		'GM' => ['Gambia', 'Gambia'],
		'GN' => ['Guinea', 'Guinea'],
		'GP' => ['Guadeloupe', 'Guadeloupe'],
		'GQ' => ['Äquatorialguinea', 'Equatorial Guinea'],
		'GR' => ['Griechenland', 'Greece'],
		'GS' => ['Südgeorgien und die Südlichen Sandwichinseln', 'South Georgia & South Sandwich Islands'],
		'GT' => ['Guatemala', 'Guatemala'],
		'GU' => ['Guam', 'Guam'],
		'GW' => ['Guinea-Bissau', 'Guinea-Bissau'],
		'GY' => ['Guyana', 'Guyana'],
		'HK' => ['Sonderverwaltungsregion Hongkong', 'Hong Kong SAR China'],
		'HM' => ['Heard und McDonaldinseln', 'Heard & McDonald Islands'],
		'HN' => ['Honduras', 'Honduras'],
		'HR' => ['Kroatien', 'Croatia'],
		'HT' => ['Haiti', 'Haiti'],
		'HU' => ['Ungarn', 'Hungary'],
		'ID' => ['Indonesien', 'Indonesia'],
		'IE' => ['Irland', 'Ireland'],
		'IL' => ['Israel', 'Israel'],
		'IM' => ['Isle of Man', 'Isle of Man'],
		'IN' => ['Indien', 'India'],
		'IO' => ['Britisches Territorium im Indischen Ozean', 'British Indian Ocean Territory'],
		'IQ' => ['Irak', 'Iraq'],
		'IR' => ['Iran', 'Iran'],
		'IS' => ['Island', 'Iceland'],
		'IT' => ['Italien', 'Italy'],
		'JE' => ['Jersey', 'Jersey'],
		'JM' => ['Jamaika', 'Jamaica'],
		'JO' => ['Jordanien', 'Jordan'],
		'JP' => ['Japan', 'Japan'],
		'KE' => ['Kenia', 'Kenya'],
		'KG' => ['Kirgisistan', 'Kyrgyzstan'],
		'KH' => ['Kambodscha', 'Cambodia'],
		'KI' => ['Kiribati', 'Kiribati'],
		'KM' => ['Komoren', 'Comoros'],
		'KN' => ['St. Kitts und Nevis', 'St. Kitts & Nevis'],
		'KP' => ['Nordkorea', 'North Korea'],
		'KR' => ['Südkorea', 'South Korea'],
		'KW' => ['Kuwait', 'Kuwait'],
		'KY' => ['Kaimaninseln', 'Cayman Islands'],
		'KZ' => ['Kasachstan', 'Kazakhstan'],
		'LA' => ['Laos', 'Laos'],
		'LB' => ['Libanon', 'Lebanon'],
		'LC' => ['St. Lucia', 'St. Lucia'],
		'LI' => ['Liechtenstein', 'Liechtenstein'],
		'LK' => ['Sri Lanka', 'Sri Lanka'],
		'LR' => ['Liberia', 'Liberia'],
		'LS' => ['Lesotho', 'Lesotho'],
		'LT' => ['Litauen', 'Lithuania'],
		'LU' => ['Luxemburg', 'Luxembourg'],
		'LV' => ['Lettland', 'Latvia'],
		'LY' => ['Libyen', 'Libya'],
		'MA' => ['Marokko', 'Morocco'],
		'MC' => ['Monaco', 'Monaco'],
		'MD' => ['Republik Moldau', 'Moldova'],
		'ME' => ['Montenegro', 'Montenegro'],
		'MF' => ['St. Martin', 'St. Martin'],
		'MG' => ['Madagaskar', 'Madagascar'],
		'MH' => ['Marshallinseln', 'Marshall Islands'],
		'MK' => ['Nordmazedonien', 'North Macedonia'],
		'ML' => ['Mali', 'Mali'],
		'MM' => ['Myanmar', 'Myanmar (Burma)'],
		'MN' => ['Mongolei', 'Mongolia'],
		'MO' => ['Sonderverwaltungsregion Macau', 'Macao SAR China'],
		'MP' => ['Nördliche Marianen', 'Northern Mariana Islands'],
		'MQ' => ['Martinique', 'Martinique'],
		'MR' => ['Mauretanien', 'Mauritania'],
		'MS' => ['Montserrat', 'Montserrat'],
		'MT' => ['Malta', 'Malta'],
		'MU' => ['Mauritius', 'Mauritius'],
		'MV' => ['Malediven', 'Maldives'],
		'MW' => ['Malawi', 'Malawi'],
		'MX' => ['Mexiko', 'Mexico'],
		'MY' => ['Malaysia', 'Malaysia'],
		'MZ' => ['Mosambik', 'Mozambique'],
		'NA' => ['Namibia', 'Namibia'],
		'NC' => ['Neukaledonien', 'New Caledonia'],
		'NE' => ['Niger', 'Niger'],
		'NF' => ['Norfolkinsel', 'Norfolk Island'],
		'NG' => ['Nigeria', 'Nigeria'],
		'NI' => ['Nicaragua', 'Nicaragua'],
		'NL' => ['Niederlande', 'Netherlands'],
		'NO' => ['Norwegen', 'Norway'],
		'NP' => ['Nepal', 'Nepal'],
		'NR' => ['Nauru', 'Nauru'],
		'NU' => ['Niue', 'Niue'],
		'NZ' => ['Neuseeland', 'New Zealand'],
		'OM' => ['Oman', 'Oman'],
		'PA' => ['Panama', 'Panama'],
		'PE' => ['Peru', 'Peru'],
		'PF' => ['Französisch-Polynesien', 'French Polynesia'],
		'PG' => ['Papua-Neuguinea', 'Papua New Guinea'],
		'PH' => ['Philippinen', 'Philippines'],
		'PK' => ['Pakistan', 'Pakistan'],
		'PL' => ['Polen', 'Poland'],
		'PM' => ['St. Pierre und Miquelon', 'St. Pierre & Miquelon'],
		'PN' => ['Pitcairninseln', 'Pitcairn Islands'],
		'PR' => ['Puerto Rico', 'Puerto Rico'],
		'PS' => ['Palästinensische Autonomiegebiete', 'Palestinian Territories'],
		'PT' => ['Portugal', 'Portugal'],
		'PW' => ['Palau', 'Palau'],
		'PY' => ['Paraguay', 'Paraguay'],
		'QA' => ['Katar', 'Qatar'],
		'RE' => ['Réunion', 'Réunion'],
		'RO' => ['Rumänien', 'Romania'],
		'RS' => ['Serbien', 'Serbia'],
		'RU' => ['Russland', 'Russia'],
		'RW' => ['Ruanda', 'Rwanda'],
		'SA' => ['Saudi-Arabien', 'Saudi Arabia'],
		'SB' => ['Salomonen', 'Solomon Islands'],
		'SC' => ['Seychellen', 'Seychelles'],
		'SD' => ['Sudan', 'Sudan'],
		'SE' => ['Schweden', 'Sweden'],
		'SG' => ['Singapur', 'Singapore'],
		'SH' => ['St. Helena', 'St. Helena'],
		'SI' => ['Slowenien', 'Slovenia'],
		'SJ' => ['Spitzbergen und Jan Mayen', 'Svalbard & Jan Mayen'],
		'SK' => ['Slowakei', 'Slovakia'],
		'SL' => ['Sierra Leone', 'Sierra Leone'],
		'SM' => ['San Marino', 'San Marino'],
		'SN' => ['Senegal', 'Senegal'],
		'SO' => ['Somalia', 'Somalia'],
		'SR' => ['Suriname', 'Suriname'],
		'SS' => ['Südsudan', 'South Sudan'],
		'ST' => ['São Tomé und Príncipe', 'São Tomé & Príncipe'],
		'SV' => ['El Salvador', 'El Salvador'],
		'SX' => ['Sint Maarten', 'Sint Maarten'],
		'SY' => ['Syrien', 'Syria'],
		'SZ' => ['Eswatini', 'Eswatini'],
		'TC' => ['Turks- und Caicosinseln', 'Turks & Caicos Islands'],
		'TD' => ['Tschad', 'Chad'],
		'TF' => ['Französische Süd- und Antarktisgebiete', 'French Southern Territories'],
		'TG' => ['Togo', 'Togo'],
		'TH' => ['Thailand', 'Thailand'],
		'TJ' => ['Tadschikistan', 'Tajikistan'],
		'TK' => ['Tokelau', 'Tokelau'],
		'TL' => ['Timor-Leste', 'Timor-Leste'],
		'TM' => ['Turkmenistan', 'Turkmenistan'],
		'TN' => ['Tunesien', 'Tunisia'],
		'TO' => ['Tonga', 'Tonga'],
		'TR' => ['Türkei', 'Türkiye'],
		'TT' => ['Trinidad und Tobago', 'Trinidad & Tobago'],
		'TV' => ['Tuvalu', 'Tuvalu'],
		'TW' => ['Taiwan', 'Taiwan'],
		'TZ' => ['Tansania', 'Tanzania'],
		'UA' => ['Ukraine', 'Ukraine'],
		'UG' => ['Uganda', 'Uganda'],
		'UM' => ['Amerikanische Überseeinseln', 'U.S. Outlying Islands'],
		'US' => ['Vereinigte Staaten', 'United States'],
		'UY' => ['Uruguay', 'Uruguay'],
		'UZ' => ['Usbekistan', 'Uzbekistan'],
		'VA' => ['Vatikanstadt', 'Vatican City'],
		'VC' => ['St. Vincent und die Grenadinen', 'St. Vincent & Grenadines'],
		'VE' => ['Venezuela', 'Venezuela'],
		'VG' => ['Britische Jungferninseln', 'British Virgin Islands'],
		'VI' => ['Amerikanische Jungferninseln', 'U.S. Virgin Islands'],
		'VN' => ['Vietnam', 'Vietnam'],
		'VU' => ['Vanuatu', 'Vanuatu'],
		'WF' => ['Wallis und Futuna', 'Wallis & Futuna'],
		'WS' => ['Samoa', 'Samoa'],
		'YE' => ['Jemen', 'Yemen'],
		'YT' => ['Mayotte', 'Mayotte'],
		'ZA' => ['Südafrika', 'South Africa'],
		'ZM' => ['Sambia', 'Zambia'],
		'ZW' => ['Simbabwe', 'Zimbabwe'],
	];
}
